name: modelmanager_aqueduct
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: any
  uuid: ^2.0.4
  mime: any
  shared_models:
    path: ../shared_models

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0