@startuml modelmanager_server
set namespaceSeparator ::

class "modelmanager_server::channel.dart::ModelManagerChannel" {
  -Database _database
  -Router _router
  +void handle()
}

"modelmanager_server::channel.dart::ModelManagerChannel" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::channel.dart::ModelManagerChannel" o-- "modelmanager_server::router.dart::Router"

class "modelmanager_server::controllers::admin_controllers.dart::StatisticController" {
  +Database database
  +Future get()
  +Future post()
}

"modelmanager_server::controllers::admin_controllers.dart::StatisticController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::admin_controllers.dart::StatisticController"

class "modelmanager_server::controllers::admin_users_container.dart::UserListController" {
  +Database database
  +Future get()
}

"modelmanager_server::controllers::admin_users_container.dart::UserListController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::admin_users_container.dart::UserListController"

class "modelmanager_server::controllers::admin_users_container.dart::UserDataController" {
  +Database database
  +Future get()
}

"modelmanager_server::controllers::admin_users_container.dart::UserDataController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::admin_users_container.dart::UserDataController"

class "modelmanager_server::controllers::admin_users_container.dart::UserDeleteController" {
  +Database database
  +Future post()
}

"modelmanager_server::controllers::admin_users_container.dart::UserDeleteController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::admin_users_container.dart::UserDeleteController"

class "modelmanager_server::controllers::admin_users_container.dart::UserModelDeleteController" {
  +Database database
  +Future post()
}

"modelmanager_server::controllers::admin_users_container.dart::UserModelDeleteController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::admin_users_container.dart::UserModelDeleteController"

class "modelmanager_server::controllers::authorisation.dart::SignupController" {
  +Database database
  +Future post()
  +Future get()
}

"modelmanager_server::controllers::authorisation.dart::SignupController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::authorisation.dart::SignupController"

class "modelmanager_server::controllers::authorisation.dart::LoginController" {
  +Future get()
  +Future post()
}

"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::authorisation.dart::LoginController"

class "modelmanager_server::controllers::controller.dart::Controller" {
  +Future get()
  +Future post()
}

class "modelmanager_server::controllers::model_controllers.dart::ModelsListController" {
  +Database database
  +Future get()
  +Future post()
}

"modelmanager_server::controllers::model_controllers.dart::ModelsListController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::model_controllers.dart::ModelsListController"

class "modelmanager_server::controllers::model_controllers.dart::AddNewModelController" {
  +Database database
  +Future post()
  +Future get()
}

"modelmanager_server::controllers::model_controllers.dart::AddNewModelController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::model_controllers.dart::AddNewModelController"

class "modelmanager_server::controllers::model_upload.dart::ModelUploadController" {
  +Database database
  +Future post()
  +Future get()
}

"modelmanager_server::controllers::model_upload.dart::ModelUploadController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::model_upload.dart::ModelUploadController"

class "modelmanager_server::controllers::restricted_controller.dart::RestrictedController" {
  +Database database
  +bool isAdminOnly
  +Future get()
  +Future post()
  +Future authorise()
  -bool _isAuthorized()
  -bool _isValidUsernameAndPassword()
  -bool _isUser()
  -bool _isAdmin()
}

"modelmanager_server::controllers::restricted_controller.dart::RestrictedController" o-- "modelmanager_server::database::database.dart::Database"
"modelmanager_server::controllers::controller.dart::Controller" <|-- "modelmanager_server::controllers::restricted_controller.dart::RestrictedController"

class "modelmanager_server::database::database.dart::Database" {
  -Uuid _uuidGenerator
  +Directory databaseDirectory
  +UsersController usersController
  +HashMap<String, ModelsDatabase> userDataDatabase
  +void saveUsers()
  +void saveUserData()
  +void saveAllUsersData()
  +Future addUser()
  +Future addModel()
  +Future addVersion()
  +IOSink newVersionSink()
  +UserModel queryName()
  +ModelsDatabase getModelsByUser()
  +int getSummaryDataSize()
  +void remove()
  +List getAllUsers()
}

"modelmanager_server::database::database.dart::Database" o-- "uuid::uuid.dart::Uuid"
"modelmanager_server::database::database.dart::Database" o-- "dart::io::Directory"
"modelmanager_server::database::database.dart::Database" o-- "modelmanager_server::database::db_models::users_controller.dart::UsersController"
"modelmanager_server::database::database.dart::Database" o-- "dart::collection::HashMap<String, ModelsDatabase>"

class "modelmanager_server::database::db_models::model_config_controller.dart::ModelsConfigController" {
  {static} -JsonCodec _jsonCodec
  +Map<String, ModelConfig> configs
  +File configFile
  +String id
  -void _readConfig()
  -void _writeConfig()
  +Future save()
  +ModelConfig []()
  +void []=()
  +void add()
  +List getConfigList()
}

"modelmanager_server::database::db_models::model_config_controller.dart::ModelsConfigController" o-- "dart::convert::JsonCodec"
"modelmanager_server::database::db_models::model_config_controller.dart::ModelsConfigController" o-- "dart::io::File"

class "modelmanager_server::database::db_models::users_controller.dart::UsersController" {
  {static} -JsonCodec _jsonCodec
  -HashMap<String, UserModel> _users
  +File configFile
  +Iterable<UserModel> users
  -void _readConfig()
  -void _writeConfig()
  +Future save()
  +bool remove()
  +void add()
}

"modelmanager_server::database::db_models::users_controller.dart::UsersController" o-- "dart::convert::JsonCodec"
"modelmanager_server::database::db_models::users_controller.dart::UsersController" o-- "dart::collection::HashMap<String, UserModel>"
"modelmanager_server::database::db_models::users_controller.dart::UsersController" o-- "dart::io::File"

class "modelmanager_server::database::models_database.dart::ModelsDatabase" {
  +Directory modelsDirectory
  +String id
  -ModelsConfigController _modelsConfig
  +int size
  +void save()
  +Future addModel()
  +Future addVersion()
  +IOSink newVersionSink()
  +List getModels()
  +ModelConfig queryName()
  +bool remove()
}

"modelmanager_server::database::models_database.dart::ModelsDatabase" o-- "dart::io::Directory"
"modelmanager_server::database::models_database.dart::ModelsDatabase" o-- "modelmanager_server::database::db_models::model_config_controller.dart::ModelsConfigController"

class "modelmanager_server::router.dart::Router" {
  +Map<Uri, List<Controller>> handlers
  +void route()
  +void handle()
}


@enduml